/** Etiquetas en español para columnas y filtros de reportes dinámicos. */
export const REPORT_FIELD_LABELS: Record<string, string> = {
  id: 'ID',
  name: 'Nombre',
  subtitle: 'Subtítulo',
  email: 'Correo electrónico',
  phone: 'Teléfono',
  mobilePhone: 'Teléfono móvil',
  role: 'Cargo',
  rut: 'RUT',
  streetAddress: 'Dirección',
  region: 'Región',
  commune: 'Comuna',
  city: 'Ciudad',
  linkedIn: 'LinkedIn',
  source: 'Origen',
  initialNote: 'Nota inicial',
  ownerName: 'Propietario',
  owner: 'Propietario',
  lastContactLabel: 'Último contacto',
  lastOutreachAt: 'Fecha último intento',
  lastOutreachChannel: 'Canal último intento',
  lastOutreachResult: 'Resultado último intento',
  lastOutreachLabel: 'Etiqueta último intento',
  reachabilityStatus: 'Contactabilidad',
  outreachAttemptCount: 'Cantidad de intentos',
  company: 'Empresa',
  companyName: 'Empresa',
  companyId: 'ID empresa',
  contactName: 'Contacto',
  contact: 'Contacto',
  contactId: 'ID contacto',
  status: 'Estado',
  industry: 'Industria',
  headquartersStreet: 'Dirección sede',
  employees: 'Empleados',
  lifecycle: 'Ciclo de vida',
  operationalStatus: 'Estado operacional',
  lastActivity: 'Última actividad',
  customerKind: 'Tipo de cliente',
  stage: 'Etapa',
  amount: 'Monto',
  amountNum: 'Monto (número)',
  weightedAmount: 'Monto ponderado',
  probability: 'Probabilidad',
  closeDate: 'Fecha cierre',
  type: 'Tipo',
  priority: 'Prioridad',
  outcome: 'Resultado',
  forecast: 'Pronóstico',
  contactEmail: 'Email contacto',
  contactPhone: 'Teléfono contacto',
  description: 'Descripción',
  decisionMaker: 'Decisor',
  competitors: 'Competidores',
  budget: 'Presupuesto',
  buyingProcess: 'Proceso de compra',
  lossReason: 'Motivo pérdida',
  primaryQuoteId: 'Cotización principal',
  title: 'Título',
  typeLabel: 'Etiqueta tipo',
  relatedType: 'Tipo relacionado',
  relatedId: 'ID relacionado',
  relatedName: 'Registro relacionado',
  due: 'Vencimiento',
  assignee: 'Asignado a',
  reminder: 'Recordatorio',
  scheduledAt: 'Programada para',
  reminderAt: 'Recordatorio en',
  sku: 'SKU',
  category: 'Categoría',
  productType: 'Tipo de producto',
  unitOfMeasure: 'Unidad de medida',
  billingPeriod: 'Periodo de facturación',
  price: 'Precio',
  priceNum: 'Precio (número)',
  priceCurrency: 'Moneda precio',
  costPrice: 'Costo',
  costPriceNum: 'Costo (número)',
  stock: 'Stock',
  stockNum: 'Stock (número)',
  barcode: 'Código de barras',
  number: 'Número',
  client: 'Cliente',
  clientName: 'Cliente',
  issueDate: 'Fecha emisión',
  dueDate: 'Fecha vencimiento',
  quoteId: 'ID cotización',
  paymentMethod: 'Forma de pago',
  siiNumber: 'Folio SII',
  progress: 'Avance',
  progressNum: 'Avance (número)',
  deadline: 'Fecha límite',
  manager: 'Responsable',
  journeyStage: 'Etapa del flujo',
  health: 'Salud',
  startDate: 'Fecha inicio',
  endDate: 'Fecha término',
  opportunityId: 'ID oportunidad',
  opportunityName: 'Oportunidad',
  acceptedQuoteId: 'Cotización aceptada',
  code: 'Código',
  validUntil: 'Válida hasta',
  reference: 'Referencia',
  supplier: 'Proveedor',
  supplierId: 'ID proveedor',
  productSummary: 'Resumen productos',
  orderDate: 'Fecha orden',
  externalReference: 'Referencia externa',
  purchaseId: 'ID compra',
  purchaseReference: 'Compra',
  purchase: 'Compra',
  confirmedAt: 'Fecha confirmación',
  warehouse: 'Bodega',
  lineCount: 'Cantidad de líneas',
  productName: 'Producto',
  product: 'Producto',
  productId: 'ID producto',
  location: 'Ubicación / bodega',
  quantity: 'Cantidad',
  quantityNum: 'Cantidad (número)',
  reservedQtyNum: 'Cantidad reservada',
  availableQtyNum: 'Cantidad disponible',
  onHandQtyNum: 'Cantidad en mano',
  minStock: 'Stock mínimo',
  minStockNum: 'Stock mínimo (número)',
  lastMovement: 'Último movimiento',
  when: 'Cuándo',
  createdAt: 'Fecha creación (original)',
  updatedAt: 'Fecha modificación (original)',
  createdAtDate: 'Fecha creación',
  updatedAtDate: 'Fecha modificación',
  createdByName: 'Creado por',
  updatedByName: 'Modificado por',
}

export function reportFieldLabel(id: string): string {
  if (REPORT_FIELD_LABELS[id]) return REPORT_FIELD_LABELS[id]!
  const dot = id.lastIndexOf('.')
  const base = dot >= 0 ? id.slice(dot + 1) : id
  if (REPORT_FIELD_LABELS[base]) return REPORT_FIELD_LABELS[base]!
  const withSpaces = id
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/_/g, ' ')
    .trim()
  return withSpaces ? withSpaces[0]!.toUpperCase() + withSpaces.slice(1) : id
}
